@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package net.cathiemomrawr.kubejsbloodmagic;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;