@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package net.cathienova.kubejsbloodmagic;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;